resources:
  repositories:
    - repository: self
      type: git
      name: Deepaklohar275/spring-petclinic
      ref: master

jobs:
  - job: Container_Scan
    steps:
      - task: SnykSecurityScan@1
        inputs:
          serviceConnectionEndpoint: 'Snyk Authentication'
          testType: 'container'
          dockerImageName: 'deepaklohar/petclini:V2'
          dockerfilePath: 'Dockerfile'
          monitorWhen: 'always'
          failOnIssues: false
        condition: succeededOrFailed()